pool:
  vmImage: 'Ubuntu-20.04'

steps:
- task: UseDotNet@2
  displayName: 'Install Core 5.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '5.x'

- script: dotnet build -c Release
  displayName: 'dotnet build Release'

- script: dotnet test -c Release
  displayName: 'dotnet test Release'
